var SELECTED_APP = 'SELECTED_APP';
var SELECTED_VERSION = 'SELECTED_VERSION';
var SELECTED_CUBE = "SELECTED_CUBE";
var SELECTED_BRANCH = "SELECTED_BRANCH";
var PROGRESS_DELAY = 300;
var DIFF_SIDE_BY_SIDE = 0;
var DIFF_INLINE = 1;
var DIFF_DESCRIPTIVE = 2;