var SELECTED_APP = 'SELECTED_APP';
var SELECTED_VERSION = 'SELECTED_VERSION';
var SELECTED_CUBE = "SELECTED_CUBE";
var SELECTED_BRANCH = "SELECTED_BRANCH";
var PROGRESS_DELAY = 300;
var DIFF_SIDE_BY_SIDE = 0;
var DIFF_INLINE = 1;
var DIFF_DESCRIPTIVE = 2;
var DIFF_VISUAL = 3;
var CLIP_NCE = '~NCE~';

var AXIS_DEFAULT = '002147483647';
var DEFAULT_TEXT = 'Default';
var CACHE_ROW_HEADER = 'rowHeader';

var BACKGROUND_CUBE_NAME = '#6495ED';
var BACKGROUND_AXIS_INFO = '#4D4D4D';
var BACKGROUND_COLUMN_HEADER = '#929292';
var BACKGROUND_ODD_ROW = '#E0E0E0';
var COLOR_WHITE = '#FFFFFF';
var CLASS_HANDSON_TABLE_HEADER = 'handsonTableHeader';
var CLASS_HANDSON_CURRENT_ROW = 'handsonCurrentRow';
var NONE = 'none';

URL_ENABLED_LIST = ['string', 'binary', 'exp', 'method', 'template'];
CACHE_ENABLED_LIST = ['string', 'binary', 'exp', 'method', 'template'];